### ISSUE TITLE
Firmata?

### ISSUE THREAD

**Issue by johnwargo** [rwaldron/javascript-robotics#21]
I'm working through the simplebot example (chapter 1) and it says "Your Arduino needs Formata on it (see Arduino)."  I have no idea what that means. What's Firmata? What does it mean that an Arduino needs Firmata on it? If I have an Arduino, how do I get Firmata on it? When you say "(see Arduino)" - see arduino where?  There's no callout or sub-topic called Arduino in the chapter that I can see.

This one sentence appears to be critical to what needs to be done, but there's absolutely no background information (none at all) I would need to understand how to act upon those instructions.  Can you please clarify what you mean here?

Also, the book says that the book's web site is at bit.ly/1KUV1p2 (with errata and so on) but when I use that URL, I'm taken to the github page which contains none of that stuff.

**Comment by dtex** [comment]
John,

Firmata is the sketch that runs on the Arduino and listens for instructions from Johnny-Five. If you have a brand new Arduino Uno, it's on there already. If you have a clone, or you've uploaded another sketch to your Arduino you will have to install Firmata. Here are the steps in a nutshell:

* Download Arduino IDE
* Plug in your Arduino or Arduino compatible microcontroller via USB
* Open the Arduino IDE, select: File > Examples > Firmata > StandardFirmata
* Click the "Upload" button

The repo here is organized by chapter but their is not much in the way of errata because frankly the book is very new and questions are just now beginning to roll in. I think your question is a very good one, applies to all the chapters, and we should put something in the readme here ASAP.

**Comment by rwaldron** [comment]
Thanks for the report @johnwargo 

The instructions that @dtex's provided are also printed in Appendix A of the book :)

**Comment by johnwargo** [comment]
Thanks, that's the information I needed. See, now you have errata to publish.

**Comment by johnwargo** [comment]
Actually, thinking about it, the repo isn't organized by chapter - if it were, it would be listed by Chapter 1, Chapter 2 and so on. The first chapter is about building a robot from low-tech materials, I couldn't find anything in the repository about that, so I had to start digging to figure out how you'd represent it here.  Of course, it didn't take me very long to remember it was called simple bot and look for it under that name. It would have been easier for me to find things based on chapter number as I knew I was in chapter 1. I expected that this project's code would be the first in the list based on how it's listed in the book. If you're going to sort by project name, put the project name in the chapter title so it's easier for me to make the connection.
